### ISSUE TITLE
show lxc-* commands executed by holodev on stdout

### ISSUE THREAD

**Issue by joenio** [lappis-tools/holodev#18]
maybe we can add a "--dummy" option to holodev not executes nothing but shows the command that would be executed.

```
# holodev --info --dummy
[HOLODEV] sudo lxc-info -n container-name
```

**Comment by chocoelho** [comment]
That'd be good :+1:

**Comment by joenio** [comment]
wip: https://github.com/lappis-tools/holodev/tree/dummy

**Comment by joenio** [comment]
done 6529ada91cc1aaad0e51a20ce4072a7b7a6688d9
