### ISSUE TITLE
 update/test opensuse package to 0.9 version

### ISSUE THREAD

**Issue by joenio** [lappis-tools/holodev#26]
@chocoelho can you do that?

**Comment by chocoelho** [comment]
Surely 😎

**Comment by chocoelho** [comment]
Just updated it :) https://build.opensuse.org/package/show/devel:tools/holodev

**Comment by chocoelho** [comment]
Also, repositories should be changed now that `holodev` is being maintained in the official `devel:tools` repository instead of my home dir.

**Comment by chocoelho** [comment]
`http://download.opensuse.org/repositories/home:/chocoelho/openSUSE_Tumbleweed/home:chocoelho.repo` should be `http://download.opensuse.org/repositories/devel:/tools/openSUSE_Tumbleweed/devel:tools.repo`. It applies to the other repos as well.
