### ISSUE TITLE
Suggestion: Transfer your repository to "lappis-tools" organization

### ISSUE THREAD

**Issue by rodrigosiqueira** [lappis-tools/holodev#4]
Hello Joenio, how are you?

Joenio, what do you think to transfer your repository to lappis-tools organization? We put all of the useful tools which were created by Lappis's members. 

I believe, we can help you with your tool. :)

See: https://github.com/lappis-tools

**Comment by joenio** [comment]
Yes, we can do that!

**Comment by joenio** [comment]
done!
